name: Java CI with Maven

on:
  push:
    branches: [ "vp-rem" ]
  pull_request:
    branches: [ "vp-rem" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Maven versioning
      uses: docker://maven:3.8.6-jdk-11
      with:
         entrypoint: /usr/local/bin/mvn-entrypoint.sh
         args:
           mvn version:set -DnewVersion=0.5.0
           mvn clean package
